# Generated by Django 3.0.8 on 2020-07-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_block',
            name='title',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Health', 'Health'), ('Sports', 'Sports'), ('Others', 'Others')], max_length=15, null=True),
        ),
    ]
