# Generated by Django 3.0.8 on 2020-07-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_writer_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_block',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
