# Generated by Django 3.0.8 on 2020-07-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Others_pics'),
        ),
    ]
