# Generated by Django 3.0.8 on 2020-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='writers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('topics', models.CharField(choices=[('Politics', 'Politics'), ('Science and Technology', 'Science and Technology'), ('Sports', 'Sports'), ('Health', 'Health')], max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='writers')),
                ('soeciality', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
