# Generated by Django 3.0.8 on 2020-07-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Writers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writers',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
