# Generated by Django 3.0.8 on 2020-07-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Writers', '0002_writers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writers',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
