# Generated by Django 3.0.8 on 2020-07-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='slug',
            field=models.SlugField(max_length=1000, null=True),
        ),
    ]
