# Generated by Django 3.0.8 on 2020-07-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0002_auto_20200724_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='slug',
            field=models.SlugField(max_length=1000, null=True, unique=True),
        ),
    ]
