# Generated by Django 3.0.8 on 2020-07-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
